apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app-deployment
spec:
  replicas: 3
  template:
    metadata:
      name: simple-app-pod
      labels:
        app: simple-app-pod
    spec:
      containers:
        - name: simple-app-container
          image: ricardodpaiva/simple-app
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /rest/v1/home
              port: 8080
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 20
          readinessProbe:
            httpGet:
              path: /rest/v1/home
              port: 8080
            periodSeconds: 10
            failureThreshold: 5
            initialDelaySeconds: 20
          resources:
            requests:
              cpu: 10m
  selector:
    matchLabels:
      app: simple-app-pod
