apiVersion: v1
kind: Service
metadata:
  name: simple-app-service-node-port
spec:
  type: NodePort
  selector:
    app: simple-app-pod
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30000