apiVersion: v1
kind: Pod
metadata:
  name: simple-app-pod
  labels:
    app: simple-app
spec:
  containers:
    - name: simple-app-pod
      image: ricardodpaiva/simple-app
      ports:
        - containerPort: 8080